name: Build and Deploy to EC2

on:
  push:
    branches: [master]  # Trigger on pushes to the main branch

jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Login to Docker Registry
#         uses: docker/login-action@v1
#         with:
#           username: faizanazim11
#           password: ${{ secrets.REGISTRY_PASSWORD }}  # Set as a secret
#       - name: Build and push image
#         uses: docker/build-push-action@v2
#         with:
#           context: .  # Path to Dockerfile
#           push: true
#           tags: faizanazim11/sa-proto1:latest
  deploy-to-ec2:
    # needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Deploy to EC2 via SSH
        env:
          INSTANCE_IP: ${{ secrets.INSTANCE_IP }}  # Store your EC2 instance IP as a secret
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your private key as a secret
          before_script: |
            - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client wget gnupg -y )'
            - wget -qO- https://get.docker.com/gpg | apt-key add -
            - eval $(ssh-agent -s)
            - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
            - mkdir -p ~/.ssh
            - touch ~/.ssh/config
            - touch ~/.ssh/known_hosts
            - chmod -R 400 ~/.ssh
            - ssh-keyscan ip >> ~/.ssh/known_hosts
            - '[[ -f /.dockerinit ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
        run: |
          docker pull faizanazim11/sa-proto1:latest
          docker-compose up -d
          EOF